enabled: true
pull_requests: true
restylers:
  - "*"
  - autopep8:
      enabled: false
  - black:
      arguments:
        - "--config"
        - "pyproject.toml"
  - isort:
      arguments:
        - "--sp"
        - "."