services:
  test_db:
    image: tnlinc/db:latest
    environment:
      POSTGRES_DB: vendor
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test
    ports:
      - 5444:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5