default:
  PROJECT_NAME: Vendor
  DEBUG: true
  PORT: 8000
  ALLOWED_HOSTS:
    - "*"
  DB_NAME:
  DB_SCHEMA:
  DB_USER:
  DB_PASSWORD:
  DB_HOST:
  DB_PORT:
  LOGSTASH_HOST:
  LOGSTASH_PORT:
  DB_URL: "@format postgresql+asyncpg://{this.DB_USER}:{this.DB_PASSWORD}@{this.DB_HOST}:{this.DB_PORT}/{this.DB_NAME}"

development:

testing:
  DEBUG: true
  ALLOWED_HOSTS:
    - "*"

heroku_prod:
  DEBUG: false
