name: Bandit
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install bandit
        run: |
          pip install bandit toml

      - name: Security check - Bandit
        id: bandit
        run: |
          mkdir -p bandit-report
          bandit -c pyproject.toml -r . -f html -o bandit-report/report.html

      - name: Upload artifacts
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: bandit_report
          path: bandit-report
