name: Pylint
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      #----------------------------------------------
      #       check-out repo and set-up python
      #----------------------------------------------
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      #----------------------------------------------
      #  -----  install & configure poetry  -----
      #----------------------------------------------
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true
      #----------------------------------------------
      # install dependencies
      #----------------------------------------------
      - name: Install dependencies
        run: |
          poetry install --no-interaction --no-root
      #----------------------------------------------
      # analise code
      #----------------------------------------------
      - name: Analysing service code with pylint
        run: |
          source .venv/bin/activate
          mkdir -p pylint_reports
          pylint * > pylint_reports/cv_pylint_checks.json || exit_code=`echo $?` || true
          pylint-json2html -o pylint_reports/cv_pylint_checks.html ./pylint_reports/cv_pylint_checks.json
          deactivate
          exit ${exit_code}
      #----------------------------------------------
      # create artifacts
      #----------------------------------------------
      - name: Upload artifacts
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: cv_pylint_report
          path: pylint_reports
