name: Pytest
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      CV_SECRET_KEY: some-secret-string
      CV_DEBUG: TRUE
      CV_ALLOWED_HOSTS: '*'
    steps:
      #----------------------------------------------
      #       check-out repo and set-up python
      #----------------------------------------------
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      #----------------------------------------------
      #  -----  install & configure poetry  -----
      #----------------------------------------------
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      #----------------------------------------------
      # install dependencies
      #----------------------------------------------
      - name: Install dependencies
        run: |
          poetry install --no-interaction --no-root

      - name: Run prebuild scripts
        run: |
          bash test/scripts/test-entrypoin.sh

      - name: Run tests
        run: |
          source .venv/bin/activate
          pytest
          deactivate
